language: python
dist: xenial
matrix:
  allow_failures:
    - os: windows
    - os: osx
  include:
    - python: 3.8
      env:
        - TOX_ENV=py38
    - python: 3.7
      env:
        - TOX_ENV=py37
    - python: 3.6
      env:
        - TOX_ENV=py36
    - python: 3.5
      env:
        - TOX_ENV=py35
    - python: 3.9-dev
      env:
        - TOX_ENV=py39
    - python: 3.6
      env:
        - TOX_ENV=pypy3.6
    - os: osx
      language: generic
      python: 3.7
      env:
        - TOX_ENV=py37
    - os: windows
      language: sh
      python: 3.8
      before_install:
        - choco install python --version=3.8.3
        - export PATH="/c/Python38:/c/Python38/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel tox
      env:
        - TOX_ENV=py38
    - python: 3.8
      env:
        - TOX_ENV=check-format
    - python: 3.8
      env:
        - TOX_ENV=flake8
    - python: 3.8
      env:
        - TOX_ENV=bandit
install:
  - pip install --upgrade tox
script:
  - tox -e $TOX_ENV
