language: python
dist: bionic
matrix:
  allow_failures:
    - os: windows
    - os: osx
    - python: 3.10-dev
  include:
    - python: 3.9
      env:
        - TOX_ENV=py39
    - python: 3.8
      env:
        - TOX_ENV=py38
    - python: 3.7
      env:
        - TOX_ENV=py37
    - python: 3.6
      env:
        - TOX_ENV=py36
    - python: 3.10-dev
      env:
        - TOX_ENV=py310
    - python: 3.6
      env:
        - TOX_ENV=pypy3.6
    - os: osx
      language: generic
      python: 3.7
      env:
        - TOX_ENV=py37
    - os: windows
      language: sh
      python: 3.9
      before_install:
        - choco install python --version=3.9.0
        - export PATH="/c/Python39:/c/Python39/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel tox
      env:
        - TOX_ENV=py39
    - python: 3.9
      env:
        - TOX_ENV=check-format
    - python: 3.9
      env:
        - TOX_ENV=flake8
    - python: 3.9
      env:
        - TOX_ENV=bandit
    - python: 3.9
      env:
        - TOX_ENV=safety
    - python: 3.9
      env:
        - TOX_ENV=coverage
before_install:
  - pip install --upgrade pip wheel tox
install:
  - python --version
  - pip --version
script:
  - tox -e $TOX_ENV
