[tox]
envlist = py310,py311,py312,py313,py314,pypy310,pypy311

[testenv]
allowlist_externals =
    find
    sed
deps =
    pytest>=9.0
    pyhamcrest>=2.0
    contexttimer>=0.3
commands =
    {posargs:py.test}

[testenv:coverage]
envlist = py314
deps =
    {[testenv]deps}
    pytest-cov>=2.5
commands =
    pytest --cov {envsitepackagesdir}/brunns --durations=10 --cov-report term-missing --cov-fail-under 100 --basetemp={envtmpdir} {posargs}
    {[cleanup]commands}
usedevelop=False

[coverage:run]
branch = True
omit = */matcher.py

[testenv:refurb]
basepython = python3
deps =
    refurb>=1.0
commands =
    refurb src/ {posargs}
usedevelop=False

[testenv:mypy]
basepython = python3
skip_install = true
deps =
    mypy~=1.0
    {[testenv]deps}
commands =
    mypy src/ {posargs}

[testenv:bandit]
basepython = python3
skip_install = true
deps =
    bandit~=1.4
commands =
    bandit -r src/

[testenv:piprot]
basepython = python3
skip_install = true
deps =
    piprot~=0.9
commands =
    pip freeze | piprot

[testenv:format]
basepython = python3
skip_install = true
deps =
    ruff
commands =
    ruff format  .
    ruff check . --target-version py310 --fix-only

[testenv:check-format]
basepython = python3
skip_install = true
deps = {[testenv:format]deps}
commands =
    ruff format . --check
    ruff check . --target-version py310

[testenv:docs]
description = invoke sphinx-build to build the HTML docs
basepython = python3
deps =
    sphinx>=3.0
    sphinx-autodoc-typehints>=1.10
    furo
commands = sphinx-build docs "{toxinidir}/build_docs" --color -W -bhtml {posargs}
           python -c 'import pathlib; print("documentation available under file://\{0\}".format(pathlib.Path(r"{toxinidir}") / "build_docs" / "index.html"))'

[cleanup]
commands =
    find {toxinidir}/tests -type f -name "*.pyc" -delete
    find {toxinidir}/tests -type d -name "__pycache__" -delete
    find {toxinidir}/src -type f -name "*.pyc" -delete
    find {toxinidir}/src -type d -name "__pycache__" -delete
    find {toxinidir}/src -type f -path "*.egg-info*" -delete
    find {toxinidir}/src -type d -path "*.egg-info" -delete
