jobs:
  build36:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run:
          name: install-tox
          command: pip install --upgrade tox
      - run:
          name: test
          command: tox -e py36
  build37:
    docker:
      - image: python:3.7
    steps:
      - checkout
      - run:
          name: install-tox
          command: pip install --upgrade tox
      - run:
          name: test
          command: tox -e py37
  build38:
    docker:
      - image: python:3.8
    steps:
      - checkout
      - run:
          name: install-tox
          command: pip install --upgrade tox
      - run:
          name: test
          command: tox -e py38
  build39:
    docker:
      - image: python:3.9
    steps:
      - checkout
      - run:
          name: install-tox
          command: pip install --upgrade tox
      - run:
          name: test
          command: tox -e py39
  check-format:
    docker:
      - image: python:3.7
    steps:
      - checkout
      - run:
          name: install-tox
          command: pip install --upgrade tox
      - run:
          name: test
          command: tox -e check-format
  flake8:
    docker:
      - image: python:3.7
    steps:
      - checkout
      - run:
          name: install-tox
          command: pip install --upgrade tox
      - run:
          name: test
          command: tox -e flake8
  bandit:
    docker:
      - image: python:3.7
    steps:
      - checkout
      - run:
          name: install-tox
          command: pip install --upgrade tox
      - run:
          name: test
          command: tox -e bandit
#  publish-coverage:
#    docker:
#      - image: python:3.7
#    steps:
#      - checkout
#      - run:
#          name: install-tox
#          command: pip install --upgrade tox
#      - run:
#          name: test
#          command: tox -e publish-coverage

workflows:
  version: 2
  tests:
    jobs:
      - build36
      - build37
      - build38
      - build39
  lint:
    jobs:
      - check-format
      - flake8
      - bandit
#      - publish-coverage
